CREATE TABLE Users (
	ID INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(20),
	LastName NVARCHAR(20),
	Email NVARCHAR(50) NOT NULL UNIQUE,
	[Address] NVARCHAR(50),
	Birthdate DATETIME,
	GenderId INT,
)

CREATE TABLE Products(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(20),
	[Description] NVARCHAR(MAX),
	Price FLOAT,
	StockNumber TINYINT
)

CREATE TABLE FavoriteProducts(
	UserId INT,
	ProductId INT,
	PRIMARY KEY(UserId, ProductID)
)

CREATE TABLE Orders(
	ID INT PRIMARY KEY IDENTITY(1,1),
	UserId INT FOREIGN KEY REFERENCES Users(Id),
	IsFinished BIT NOT NULL DEFAULT(0),
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE())
)

CREATE TABLE OrderItems(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ProductId INT FOREIGN KEY REFERENCES Products(Id),
	OrderId INT FOREIGN KEY REFERENCES Orders(Id),
	Quantity INT NOT NULL,
)

CREATE TABLE Roles(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(20) NOT NULL
	)

CREATE TABLE UsersRoles(
	UserId INT FOREIGN KEY REFERENCES Users(Id),
	RoleId INT FOREIGN KEY REFERENCES Roles(Id)
	)